all: SinglyLinkedList

SinglyLinkedList: SinglyLinkedList.cpp
	g++ -Wreturn-type -pedantic -pedantic-errors -Wundef -std=c++20 -o SinglyLinkedList SinglyLinkedList.cpp

clean:
	${RM} *.o SinglyLinkedList
